# Generated by Django 3.2.12 on 2022-04-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
