# Generated by Django 3.2.12 on 2022-04-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Add blog post snippet here, so that users understand what the post is about', max_length=255),
        ),
    ]
